# Generated by Django 4.2.5 on 2023-09-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_client', to=settings.AUTH_USER_MODEL, verbose_name='добавил клиента')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='время начала рассылки')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='время окончания')),
                ('period', models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], max_length=50, verbose_name='периодичность рассылки')),
                ('status', models.CharField(choices=[('create', 'Создана'), ('in_process', 'Запущена'), ('finished', 'Завершена')], default='create', max_length=50, verbose_name='статус рассылки')),
                ('client', models.ManyToManyField(related_name='get_client', to='mailings.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_mailings', to='mailings.mailsettings', verbose_name='рассылка')),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='добавил клиента')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='рассылка'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='дата последней попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], default='success', verbose_name='статус')),
                ('answer_server', models.TextField(verbose_name='ответ сервера')),
                ('mailings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_log', to='mailings.mailsettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
