# Generated by Django 4.2.5 on 2023-10-07 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_mail', to=settings.AUTH_USER_MODEL, verbose_name='Добавил рассылку'),
        ),
        migrations.AddField(
            model_name='logs',
            name='mailings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_log', to='mailings.mailsettings', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_client', to=settings.AUTH_USER_MODEL, verbose_name='добавил клиента'),
        ),
    ]
