# Generated by Django 4.2.5 on 2023-09-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_owner',
        ),
    ]
