# Generated by Django 4.2.5 on 2023-09-25 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailings', '0004_mailsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsettings',
            name='client',
            field=models.ManyToManyField(related_name='get_client', to='mailings.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='period',
            field=models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='status',
            field=models.CharField(choices=[('create', 'Создана'), ('in_process', 'Запущена'), ('finished', 'Завершена')], default='create', max_length=50, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_mail', to=settings.AUTH_USER_MODEL, verbose_name='Добавил рассылку'),
        ),
    ]
